"use client";
import { useEffect, useState } from "react";

type Project = { title:string; description:string; banner:string; tags:string[]; url:string; linkLabel:string };
type Skill = { group:string; name:string; level:number };
type Content = { name:string; role:string; available:string; heroDescription:string; aboutDescription:string; email:string; github:string; skills:Skill[]; projects:Project[]; process:{title:string;description:string}[]; marquee:string[]; stats:{value:string;label:string}[] };
const blankProject=():Project=>({title:"",description:"",banner:"",tags:[],url:"",linkLabel:"View project"});
const blankSkill=():Skill=>({group:"Frontend",name:"",level:50});
const emptyContent:Content={name:"",role:"",available:"",heroDescription:"",aboutDescription:"",email:"",github:"",skills:[],projects:[],process:[],marquee:[],stats:[]};
type Tab="projects"|"skills"|"profile"|"more";

export default function Admin({authenticated,configured}:{authenticated:boolean;configured:boolean}) {
 const [logged,setLogged]=useState(authenticated),[password,setPassword]=useState(""),[content,setContent]=useState<Content>(emptyContent),[tab,setTab]=useState<Tab>("projects"),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[project,setProject]=useState<Project>(blankProject()),[projectIndex,setProjectIndex]=useState(-1),[skill,setSkill]=useState<Skill>(blankSkill()),[skillIndex,setSkillIndex]=useState(-1),[uploading,setUploading]=useState(false);
 async function load(){const r=await fetch("/api/content");const d=await r.json();if(!r.ok)throw new Error(d.error||"Could not load content.");setContent(d);}
 useEffect(()=>{if(authenticated) void load().catch(e=>setMessage(e.message));},[authenticated]);
 async function login(e:React.FormEvent){e.preventDefault();setBusy(true);const r=await fetch("/api/auth/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({password})});const d=await r.json();setBusy(false);if(r.ok){setLogged(true);setMessage("");try{await load()}catch(err){setMessage(err instanceof Error?err.message:"Could not load content.")}}else setMessage(d.error);}
 async function publish(){setBusy(true);setMessage("");try{const r=await fetch("/api/content",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(content)});const d=await r.json();if(!r.ok)throw new Error(d.error||"Could not save changes.");setMessage("Saved and published. Your live portfolio will show these changes.");}catch(e){setMessage(e instanceof Error?e.message:"Could not save changes.")}finally{setBusy(false)}}
 async function logout(){await fetch("/api/auth/logout",{method:"POST"});setLogged(false)}
 async function upload(file?:File){if(!file)return;if(file.size>4*1024*1024){setMessage("Choose an image under 4 MB.");return}setUploading(true);setMessage("");const form=new FormData();form.append("file",file);try{const r=await fetch("/api/uploads",{method:"POST",body:form});const d=await r.json();if(!r.ok)throw new Error(d.error||"Upload failed.");setProject(p=>({...p,banner:d.url}));setMessage("Banner uploaded. Publish your changes to attach it to this project.")}catch(e){setMessage(e instanceof Error?e.message:"Upload failed.")}finally{setUploading(false)}}
 function saveProject(e:React.FormEvent){e.preventDefault();const next=[...content.projects];if(projectIndex<0)next.push(project);else next[projectIndex]=project;setContent({...content,projects:next});setProject(blankProject());setProjectIndex(-1);setMessage("Project added to your draft. Select Publish changes to make it live.")}
 function editProject(i:number){setProjectIndex(i);setProject({...content.projects[i],tags:[...content.projects[i].tags]});window.scrollTo({top:0,behavior:"smooth"})}
 function removeProject(i:number){if(!window.confirm("Remove this project from your portfolio?"))return;setContent({...content,projects:content.projects.filter((_,n)=>n!==i)});setMessage("Project removed from draft. Publish changes to update the live site.")}
 function moveProject(i:number,step:number){const j=i+step;if(j<0||j>=content.projects.length)return;const next=[...content.projects];[next[i],next[j]]=[next[j],next[i]];setContent({...content,projects:next})}
 function saveSkill(e:React.FormEvent){e.preventDefault();const next=[...content.skills];if(skillIndex<0)next.push(skill);else next[skillIndex]=skill;setContent({...content,skills:next});setSkill(blankSkill());setSkillIndex(-1);setMessage("Skill updated in your draft. Publish changes to update its progress bar.")}
 function removeSkill(i:number){setContent({...content,skills:content.skills.filter((_,n)=>n!==i)});setMessage("Skill removed from draft. Publish changes to update the portfolio.")}
 const update=(key:keyof Content,value:any)=>setContent(c=>({...c,[key]:value}));
 return <main className="admin-shell"><aside className="admin-rail"><a className="admin-brand" href="/">M<span>.</span>DEV</a><div className="admin-rail-note">PORTFOLIO<br/>CONTROL ROOM</div>{(["projects","skills","profile","more"] as Tab[]).map((t,i)=><button key={t} className={`rail-link ${tab===t?"active":""}`} onClick={()=>setTab(t)}>{["▣","◒","◎","＋"][i]} &nbsp; { ["Projects","Skills","Profile","More content"][i]}</button>)}<a className="rail-link" href="/">↗ &nbsp; View portfolio</a><div className="rail-bottom">PRIVATE WORKSPACE<br/>VERCEL READY</div></aside><section className="admin-main"><header className="admin-top"><span>YOUR SPACE / CONTENT</span><span className="live-pill"><i/> PORTFOLIO MANAGER</span></header>{!logged?<div className="login-wrap"><div className="eyebrow">OWNER ACCESS / 01</div><h1>Welcome<br/><em>back.</em></h1><p>Sign in to manage what the world sees.</p>{!configured&&<div className="admin-notice">Set <code>ADMIN_PASSWORD</code> and <code>ADMIN_SECRET</code> in <code>.env.local</code> before signing in.</div>}<form onSubmit={login}><label>ADMIN PASSWORD</label><input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Enter your password"/><button disabled={busy||!configured}>{busy?"CHECKING…":"ENTER DASHBOARD ↗"}</button></form>{message&&<div className="admin-message">{message}</div>}</div>:<><div className="admin-heading"><div><div className="eyebrow">CONTENT MANAGEMENT / 02</div><h1>Shape your <em>story.</em></h1><p>Edit with forms, then publish when you’re ready.</p></div><button className="logout" onClick={logout}>SIGN OUT ↗</button></div><div className="admin-toolbar"><span>{message||"Your edits stay in draft until you publish."}</span><button onClick={publish} disabled={busy}>{busy?"SAVING…":"PUBLISH CHANGES ↗"}</button></div>
 {tab==="projects"&&<section className="admin-section"><div className="section-kicker">PROJECTS / {content.projects.length} ITEMS</div><div className="form-card"><div className="form-title">{projectIndex<0?"Add a project":"Edit project"}</div><form onSubmit={saveProject} className="admin-form"><label>PROJECT TITLE<input required value={project.title} onChange={e=>setProject({...project,title:e.target.value})} placeholder="e.g. AI-powered learning platform"/></label><label>DESCRIPTION<textarea required rows={3} value={project.description} onChange={e=>setProject({...project,description:e.target.value})} placeholder="What does it do? What did you build?"/></label><div className="form-two"><label>TECH STACK<input value={project.tags.join(", ")} onChange={e=>setProject({...project,tags:e.target.value.split(",").map(x=>x.trim()).filter(Boolean)})} placeholder="Next.js, Supabase, Stripe"/><small>Separate technologies with commas.</small></label><label>PROJECT LINK<input type="url" value={project.url} onChange={e=>setProject({...project,url:e.target.value})} placeholder="https://github.com/…"/></label></div><div className="form-two"><label>LINK BUTTON LABEL<input value={project.linkLabel} onChange={e=>setProject({...project,linkLabel:e.target.value})} placeholder="View project"/></label><label>PROJECT BANNER<div className="upload-box">{project.banner?<img className="banner-preview" src={project.banner} alt="Project banner preview"/>:<div className="upload-placeholder">▧ <span>Choose an image to upload</span><small>JPG, PNG, WebP, AVIF or GIF · max 4 MB</small></div>}<input type="file" accept="image/jpeg,image/png,image/webp,image/avif,image/gif" onChange={e=>void upload(e.target.files?.[0])} disabled={uploading}/>{uploading&&<small>Uploading securely…</small>}</div></label></div><div className="form-actions"><button type="submit">{projectIndex<0?"ADD PROJECT TO DRAFT":"UPDATE PROJECT"}</button>{projectIndex>=0&&<button type="button" className="secondary" onClick={()=>{setProject(blankProject());setProjectIndex(-1)}}>CANCEL</button>}</div></form></div><div className="project-list">{content.projects.map((p,i)=><article className="managed-item" key={`${p.title}-${i}`}><div className="managed-thumb">{p.banner?<img src={p.banner} alt=""/>:<span>PROJECT<br/>BANNER</span>}</div><div className="managed-info"><b>{p.title}</b><p>{p.description}</p><small>{p.tags.join(" · ")}</small></div><div className="item-actions"><button aria-label="Move up" onClick={()=>moveProject(i,-1)}>↑</button><button aria-label="Move down" onClick={()=>moveProject(i,1)}>↓</button><button onClick={()=>editProject(i)}>EDIT</button><button className="danger" onClick={()=>removeProject(i)}>REMOVE</button></div></article>)}</div></section>}
 {tab==="skills"&&<section className="admin-section"><div className="section-kicker">SKILLS / PROGRESS TRACKING</div><div className="form-card"><div className="form-title">{skillIndex<0?"Add a skill":"Update skill"}</div><form onSubmit={saveSkill} className="admin-form"><div className="form-two"><label>SKILL NAME<input required value={skill.name} onChange={e=>setSkill({...skill,name:e.target.value})} placeholder="e.g. TypeScript"/></label><label>GROUP<input list="skill-groups" required value={skill.group} onChange={e=>setSkill({...skill,group:e.target.value})} placeholder="Frontend"/><datalist id="skill-groups">{[...new Set(content.skills.map(s=>s.group))].map(g=><option key={g} value={g}/>)}</datalist></label></div><label className="progress-label">PROGRESS <strong>{skill.level}%</strong><input className="progress-range" type="range" min="0" max="100" value={skill.level} onChange={e=>setSkill({...skill,level:Number(e.target.value)})}/><small>Choose the progress level shown on your portfolio.</small></label><div className="form-actions"><button type="submit">{skillIndex<0?"ADD SKILL":"UPDATE SKILL"}</button>{skillIndex>=0&&<button type="button" className="secondary" onClick={()=>{setSkill(blankSkill());setSkillIndex(-1)}}>CANCEL</button>}</div></form></div><div className="managed-skill-list">{content.skills.map((s,i)=><article className="managed-skill" key={`${s.name}-${i}`}><div><b>{s.name}</b><small>{s.group}</small></div><strong>{s.level}%</strong><div className="skill-preview"><i style={{width:`${s.level}%`}}/></div><button onClick={()=>{setSkillIndex(i);setSkill({...s})}}>EDIT</button><button className="danger" onClick={()=>removeSkill(i)}>REMOVE</button></article>)}</div></section>}
 {tab==="profile"&&<section className="admin-section"><div className="section-kicker">PROFILE / CONTACT / HERO</div><div className="form-card"><div className="form-title">Your portfolio introduction</div><div className="admin-form"><label>YOUR NAME<input value={content.name} onChange={e=>update("name",e.target.value)}/></label><label>ROLE / TYPEWRITER HEADLINE<input value={content.role} onChange={e=>update("role",e.target.value)}/></label><label>AVAILABILITY BADGE<input value={content.available} onChange={e=>update("available",e.target.value)}/></label><label>HERO DESCRIPTION<textarea rows={3} value={content.heroDescription} onChange={e=>update("heroDescription",e.target.value)}/></label><label>ABOUT DESCRIPTION<textarea rows={5} value={content.aboutDescription} onChange={e=>update("aboutDescription",e.target.value)}/></label><div className="form-two"><label>EMAIL<input type="email" value={content.email} onChange={e=>update("email",e.target.value)}/></label><label>GITHUB PROFILE URL<input type="url" value={content.github} onChange={e=>update("github",e.target.value)}/></label></div></div></div></section>}
 {tab==="more"&&<section className="admin-section"><div className="section-kicker">OTHER PORTFOLIO CONTENT</div><div className="form-card"><div className="form-title">Process steps</div>{content.process.map((p,i)=><div className="repeat-row" key={i}><input aria-label="Step title" value={p.title} onChange={e=>update("process",content.process.map((x,n)=>n===i?{...x,title:e.target.value}:x))}/><input aria-label="Step description" value={p.description} onChange={e=>update("process",content.process.map((x,n)=>n===i?{...x,description:e.target.value}:x))}/><button className="danger" onClick={()=>update("process",content.process.filter((_,n)=>n!==i))}>×</button></div>)}<button className="secondary" onClick={()=>update("process",[...content.process,{title:"New step",description:"Describe this step"}])}>+ ADD PROCESS STEP</button></div><div className="form-card"><div className="form-title">Stats shown in About</div>{content.stats.map((s,i)=><div className="repeat-row" key={i}><input aria-label="Stat value" value={s.value} onChange={e=>update("stats",content.stats.map((x,n)=>n===i?{...x,value:e.target.value}:x))}/><input aria-label="Stat label" value={s.label} onChange={e=>update("stats",content.stats.map((x,n)=>n===i?{...x,label:e.target.value}:x))}/><button className="danger" onClick={()=>update("stats",content.stats.filter((_,n)=>n!==i))}>×</button></div>)}<button className="secondary" onClick={()=>update("stats",[...content.stats,{value:"0",label:"New stat"}])}>+ ADD STAT</button></div><div className="form-card"><div className="form-title">Scrolling tech marquee</div><label className="admin-form">WORDS <input value={content.marquee.join(", ")} onChange={e=>update("marquee",e.target.value.split(",").map(x=>x.trim()).filter(Boolean))}/><small>Separate words with commas.</small></label></div></section>}
 </>}</section></main>
}
